<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '#' => '',
    'Requests to support' => 'Запросы в службу поддержки',
    'Active' => 'Активный',
    'Answered' => 'Отвечено',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить элемент?',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Category updated successfully.' => 'Категория успешно обновлена.',
    'Close' => 'Закрыть',
    'Content updated.' => 'Контент обновлен.',
    'Contents' => 'Содержимое',
    'Create' => 'Создать',
    'Create Support Category' => 'Добавить категорию',
    'Create Support Request' => 'Отправить запрос в поддержку',
    'Created' => 'Создано',
    'Created At' => 'Создано',
    'Critical' => 'Критический',
    'Danger' => 'Опасный',
    'Delete' => 'Удалить',
    'Deleted' => 'Удалено',
    'Draft' => 'Черновик',
    'Email' => 'Email',
    'Error' => 'Ошибка',
    'File:' => 'Файл:',
    'Filename' => 'Имя файла',
    'Fio' => 'ФИО',
    'ID' => '№',
    'Icon' => 'Значок',
    'Info' => 'Информационный',
    'Level' => 'Уровень',
    'Message' => 'Сообщение',
    'Notice' => 'Замечание',
    'Parent' => 'Родитель',
    'Requests' => 'Запрос',
    'Save' => 'Сохранить',
    'Sending' => 'Отправлено',
    'Sending At' => 'Отправлено',
    'Status' => 'Статус',
    'Support' => 'Поддержка',
    'Support Categories' => 'Категории',
    'Support Requests' => 'Запросы',
    'Ticket ID' => '№',
    'Title' => 'Название',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Update Content: {nameAttribute}' => 'Обновить контент',
    'Update Support Category: {nameAttribute}' => 'Обновить категорию',
    'Update Support Request: {nameAttribute}' => 'Обновить запрос',
    'User' => 'Пользователь',
    'User ID' => 'ID пользователя',
    'Waiting' => 'Ожидание',
    'Warning' => 'Предупреждение',
    'You answer saved successfully.' => 'Ответ успешно сохранен.',
    'You category saved successfully.' => 'Категорию усешно сохранена.',
    'You not allowed this action.' => 'Вам не разрешено это действие.',
    'You request saved successfully.' => 'Запрос успешно создан.',
    'You request updated successfully.' => 'Запрос успешно обновлен.',
];
